### ISSUE TITLE
Move community examples to AdoptOpenJDK (or some other Java image)

### ISSUE THREAD

**Issue by rdruss** [openshift-vertx-examples/issues#5]
Need to determine what the appropriate community recommendation would be.  What are the right criteria for this decision.

**Comment by jponge** [comment]
I'm using `adoptopenjdk/openjdk11:ubi-minimal-jre` in the _Vert.x in Action_ (upcoming) examples, and some Jib configuration like:

```kotlin
jib {
  from {
    image = "adoptopenjdk/openjdk11:ubi-minimal-jre"
  }
  to {
    image = "vertx-in-action/heat-sensor"
    tags = setOf("v1", "latest")
  }
  container {
    mainClass = "chapter13.sensor.HeatSensor"
    jvmFlags = listOf("-noverify", "-Djava.security.egd=file:/dev/./urandom")
    ports = listOf("8080", "5701")
    user = "nobody:nobody"
  }
}
```

**Comment by rdruss** [comment]
I think for now we will use the ubi8/openjdk-11 image by default.  This smoothes the transition between community and production (i.e. we can use the same Java builder image).  @jponge, wdyt?

**Comment by jponge** [comment]
LGTM 👍
